import { nanoid } from "nanoid";

export const links = [
  { id: nanoid(), href: "#home", text: "home" },
  { id: nanoid(), href: "#about", text: "about" },
  { id: nanoid(), href: "#training", text: "training" },
  { id: nanoid(), href: "#event", text: "event" },
];

export const trains = [
  {
    id: nanoid(),
    title: "week 1 - w/c 11.03.2024",
    distance: "25.52km",
    duration: "1h 16m",
    elevation: "165m",
    comments: "First Strava ride!",
  },
  {
    id: nanoid(),
    title: "week 2 - w/c 18.03.2024",
    distance: "33.80km",
    duration: "1h 33m",
    elevation: "181m",
    comments: "",
  },
  {
    id: nanoid(),
    title: "week 3 - w/c 25.03.2024",
    distance: "0km",
    duration: "0h 0m",
    elevation: "0m",
    comments: "Bike in for service",
  },
  {
    id: nanoid(),
    title: "week 4 - w/c 01.04.2024",
    distance: "59.09km",
    duration: "2h 53m",
    elevation: "418m",
    comments: "",
  },
  {
    id: nanoid(),
    title: "week 5 - w/c 08.04.2024",
    distance: "31.94km",
    duration: "1h 36m",
    elevation: "331m",
    comments: "Trying out new training route.",
  },
  {
    id: nanoid(),
    title: "week 6 - w/c 15.04.2024",
    distance: "83.50km",
    duration: "4h 11m",
    elevation: "738m",
    comments: "",
  },
  {
    id: nanoid(),
    title: "week 7 - w/c 22.04.2024",
    distance: "60.53km",
    duration: "3h 7m",
    elevation: "339m",
    comments:
      "First loop of Annecy - bit cold.  Started taking advantage of the indoor trainer on wet days",
  },
  {
    id: nanoid(),
    title: "week 8 - w/c 29.04.2024",
    distance: "117.53km",
    duration: "5h 17m",
    elevation: "482m",
    comments: "Solo ride to Albertville, with descent from Hautecour.",
  },
  {
    id: nanoid(),
    title: "week 9  - w/c 06.05.2024",
    distance: "179.16km",
    duration: "7h 48m",
    elevation: "958m",
    comments:
      "Solo ride to Annecy.  False flat was hard work from Ugine with the wind.",
  },
  {
    id: nanoid(),
    title: "week 10  - w/c 13.05.2024",
    distance: "103.42km",
    duration: "5h 17m",
    elevation: "247m",
    comments:
      "Solo ride to Albertville to collect new car and gentle ride in Nice.",
  },
  {
    id: nanoid(),
    title: "week 11 - w/c 20.05.2024",
    distance: "69.73km",
    duration: "3h 39m",
    elevation: "468m",
    comments: "Training continues in Norfolk, on my old Trek mountain bike.",
  },
  {
    id: nanoid(),
    title: "week 12 - w/c 27.05.2024",
    distance: "65.60km",
    duration: "3h 1m",
    elevation: "651m",
    comments: "First ride joined with Cedric",
  },
  {
    id: nanoid(),
    title: "week 13 - w/c 03.06.2024",
    distance: "198.42km",
    duration: "8h 39m",
    elevation: "1,148m",
    comments: "Annecy loop from Albertville with Rach.",
  },
  {
    id: nanoid(),
    title: "week 14 - w/c 10.06.2024",
    distance: "174.59km",
    duration: "8h 58m",
    elevation: "2,051m",
    comments:
      "First col with Rach - Col de Tamie.  Saw Jonas Vingegaard, Christopher LaPorte and Wout van Aert on a training ride.",
  },
  {
    id: nanoid(),
    title: "week 15 - w/c 17.06.2024",
    distance: "180.37km",
    duration: "10h 17m",
    elevation: "2,916m",
    comments:
      "First tumble of training.  Plus a very hot and steep training ride with Rach. Col de la Forclaz.",
  },
  {
    id: nanoid(),
    title: "week 16 - w/c 24.06.2024",
    distance: "297.50km",
    duration: "13h 29m",
    elevation: "2,833m",
    comments: "First solo 100km.  Plus Col de Leschaux.",
  },
  {
    id: nanoid(),
    title: "week 17 - w/c 01.07.2024",
    distance: "241.19km",
    duration: "11h 49m",
    elevation: "2,566m",
    comments: "First solo 150km.",
  },
  {
    id: nanoid(),
    title: "week 18 - w/c 08.07.2024",
    distance: "164.60km",
    duration: "10h 28m",
    elevation: "3,530m",
    comments: "Petit St Bernard with Cedric, Rach and Sam",
  },
  {
    id: nanoid(),
    title: "week 19 - w/c 15.07.2024",
    distance: "223.3km",
    duration: "10h 6m",
    elevation: "1,898m",
    comments: "First climb to the house (Hautecour).",
  },
  {
    id: nanoid(),
    title: "week 20 - w/c 22.07.2024",
    distance: "76.6km",
    duration: "4h 13m",
    elevation: "1,087m",
    comments: "Pink road up from Seez, TDF route.  UK trip.",
  },
  {
    id: nanoid(),
    title: "week 21 - w/c 29.07.2024",
    distance: "266.62km",
    duration: "14h 50m",
    elevation: "4,305m",
    comments: "Very hot week, Col de la Madeline. Plus few climbs to Hautecour",
  },
  {
    id: nanoid(),
    title: "week 22 - w/c 05.08.2024",
    distance: "0km",
    duration: "0h 0m",
    elevation: "0m",
    comments:
      "Unable to train this week due to illness.  First major set back of training.  Hoping to bounce back next week.",
  },
];

export const events = [
  {
    id: nanoid(),
    date: "21.08.2024",
    route: "Meribel to Meribel",
    distance: "76km",
    climb: "2,391m",
  },
  {
    id: nanoid(),
    date: "22.08.2024",
    route: "Meribel to Aosta",
    distance: "145.6km",
    climb: "2,857m",
  },
  {
    id: nanoid(),
    date: "23.08.2024",
    route: "Aosta to Verbier",
    distance: "79.7km",
    climb: "2,763m",
  },
  {
    id: nanoid(),
    date: "24.08.2024",
    route: "Verbier to Chamonix",
    distance: "76km",
    climb: "2,391m",
  },
];
